[package]
name = "caligo"
version = "0.1.0"
edition = "2024"
rust-version = "1.88"

[target.'cfg(target_os = "windows")'.dependencies]
gpui = { version = "=0.2.2", default-features = false, features = ["windows-manifest"] }

[target.'cfg(not(target_os = "windows"))'.dependencies]
gpui = { version = "=0.2.2", default-features = false, features = ["x11", "font-kit"] }

[profile.release]
lto = "thin"
strip = true